#!/bin/bash
p=
while :; do
	inotifywait -qre modify server.c
	make
	if [ $? -ne 0 ]; then
		echo ----------------
		echo
		continue
	fi
	if [ ! -z $p ]; then
		kill -9 $p
		p=
	fi
	./server &
	p=$!
done
